Website Brand Redesign
working-group-two/wgtwo.com pull request #310
Opened 2023-04-13 19:35 UTC by Prid13

#### Style

- Primary Buttons colors changed
- All black boxes changed to aurora green, with internation blue text on top
  - Also, some tweaks have been made to accomodate for this change (some transparency values, color, borders, etc.)
- Light blue pills changed to light aurora green

##### Images
- New Logo added
- All instances of Logos changed (social media image, favicons, etc.)
- Author image added for wgtwo

##### Fonts
- English and Japanese fonts separated (Inter for en, Noto Sans JP for jp)
  - NB: wasn't able to limit the JP font to only JP characters, so the whole JP website uses a different font. To solve this, a custom font would have to be self-hosted on WG2 servers to limit the JP font to only JP characters, and thus Google's servers wouldn't be used (not sure how good of a solution is this)

#### Names
- "Working Group Two" => "WG2"
  - Q: was I supposed to do this? or only wgtwo?
- "wgtwo" => "WG2"

###### Exceptions
- Legal instances ("Working Group Two AS")
- old blog posts mentioning "Working Group Two"/"Wgtwo"
  - Q: should they be untouched for posterity/integrity?

#### URLs
- wgtwo.com => wg2.com
- github.com/working-group-two/wgtwo.com => https
- github.com/working-group-two/wg2.com

###### Exceptions
- subdomains like developer.wgtwo.com
- external services like wgtwo.jobs.personio.de

2023-04-13 19:51 UTC, Prid13 commented
Build Website is failing bc I've changed "wgtwo.com" to "wg2.com" and also the github repo name to "wg2.com". Ignore it

2023-04-28 10:11 UTC, jonny-wg2 requested changes
Great work @Prid13  - it's a lot!!

I left a couple comments. Let's make the changes to revert some lines in the docusaurus.config.js. It would be best to do a staged deployment where we make this go live with wgtwo.com and then we make the changes to change the domain to wg2.com

2023-04-28 10:11 UTC, jonny-wg2 commented on website/docusaurus.config.js
> -  organizationName: "working-group-two",
keep this for now

2023-04-28 10:11 UTC, jonny-wg2 commented on website/docusaurus.config.js
> -  projectName: "wgtwo.com",
keep this wgtwo.com for now. we will do a staged deployment.

2023-04-28 10:11 UTC, jonny-wg2 commented on website/docusaurus.config.js
> -            "https://github.com/working-group-two/wgtwo.com/edit/main/docs/",
keep for now

2023-04-28 10:11 UTC, jonny-wg2 commented on website/docusaurus.config.js
> -            "https://github.com/working-group-two/wgtwo.com/edit/main/blog/",
keep for now

2023-05-01 03:06 UTC, Prid13 commented
@jonny-wg2 thanks, done :)

2023-11-14 11:24 UTC, closed without merging