Brand Page
working-group-two/wgtwo.com pull request #318
Opened 2023-04-28 04:33 UTC by Prid13

Access at: [wgtwo-dev.netlify.app **/brand**](https://wgtwo-dev.netlify.app/brand)

- Complete replica of https://menu-accept-258355.framer.app/
- NOT yet mobile-friendly
- Would need slight tweaking before migrating to separate subdomain (outside of Docusaurus/React)

Also, I noticed that one color is missing from the framer page: Aurora Purple Lighten 3 and 4 are identitcal!

2023-04-28 13:36 UTC, jonny-wg2 requested changes

2023-04-28 13:36 UTC, jonny-wg2 commented on website/src/pages/brand/index.tsx
> +          Download all WG2 logos
Can you make the download link https://drive.google.com/drive/folders/1gm13n5gH7qRm2jDe9bSRBydNc9xMGBjv

2023-05-12 10:00 UTC, jonny-wg2 requested changes
I used this page over the week and was super helpful! One nice feature would be adding a download link to download inter / the font. https://fonts.google.com/specimen/Inter. I had the usecase where I was doing something in photoshop and didn't have the link downloaded locally.

Once we make it mobile friendly let's give it a merge!

2023-05-12 11:18 UTC, torotimes commented
Hi @jonny-wg2 

Good suggestion. 

@Prid13 wanna have a look at that? 

Tor

2023-05-16 05:52 UTC, Prid13 commented
Done :)

<img width="947" alt="Screenshot_7381" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/a493a29d-4a42-477a-98ea-778390b03321">

Another variant:

<img width="950" alt="Screenshot_7376" src="https://github.com/working-group-two/wgtwo.com/assets/27897747/3e95924e-e961-4c24-ba64-a19029bc2f9c">

2023-05-16 05:53 UTC, Prid13 commented
I've also made the page a bit mobile friendly, _except_ for the navbar. Don't know how to avoid using a hamburger menu 😅

2023-05-16 09:29 UTC, torotimes approved these changes

2023-05-16 09:30 UTC, torotimes commented
@jonny-wg2 are you ok to merge this one?

2023-05-16 09:37 UTC, jonny-wg2 approved these changes
🤟🏻

2023-05-16 09:37 UTC, merged

2023-05-16 09:37 UTC, jonny-wg2 commented
Looks great! Just merged